-- MySQL Script generated by MySQL Workbench
-- Ter 09 Ago 2016 23:14:01 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET latin1 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`TIPOQUARTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`TIPOQUARTO` (
  `idTipoQuarto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoQuarto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`ENDERECO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`ENDERECO` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(9) NOT NULL,
  `complemento` VARCHAR(20) NULL,
  `bairro` VARCHAR(20) NOT NULL,
  `cidade` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `cep` VARCHAR(20) NOT NULL,
  `pais` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`HOTEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`HOTEL` (
  `idHotel` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(15) NOT NULL,
  `nomeFantasia` VARCHAR(20) NOT NULL,
  `idEndereco` INT NOT NULL,
  PRIMARY KEY (`idHotel`),
  UNIQUE INDEX `UNIQUE` (`cnpj` ASC),
  INDEX `fk_HOTEL_ENDERECO` (`idEndereco` ASC),
  CONSTRAINT `fk_HOTEL_ENDERECO`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `hotel`.`ENDERECO` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`QUARTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`QUARTO` (
  `idQuarto` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(10) NOT NULL,
  `posicao` ENUM('VIRADO PARA A PRAIA','VIRADO PARA A PISCINA','NORMAL') NOT NULL DEFAULT 'NORMAL',
  `situacao` ENUM('LIVRE','OCUPADO','EM LIMPEZA','EM MANUTENCAO','FECHADO') NOT NULL DEFAULT 'FECHADO',
  `idTipoQuarto` INT NOT NULL,
  `idHotel` INT NOT NULL,
  PRIMARY KEY (`idQuarto`),
  INDEX `fk_TIPOQUARTO` (`idTipoQuarto` ASC),
  INDEX `fk_QUARTO_HOTEL` (`idHotel` ASC),
  CONSTRAINT `fk_TIPOQUARTO`
    FOREIGN KEY (`idTipoQuarto`)
    REFERENCES `hotel`.`TIPOQUARTO` (`idTipoQuarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QUARTO_HOTEL`
    FOREIGN KEY (`idHotel`)
    REFERENCES `hotel`.`HOTEL` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`PESSOA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`PESSOA` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `idEndereco` INT NOT NULL,
  PRIMARY KEY (`idPessoa`),
  INDEX `fk_PESSOA_ENDERECO` (`idEndereco` ASC),
  CONSTRAINT `fk_PESSOA_ENDERECO`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `hotel`.`ENDERECO` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`CLIENTE` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(14) NOT NULL,
  `identidade` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NULL,
  `idPessoa` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_CLIENTE_PESSOA` (`idPessoa` ASC),
  CONSTRAINT `fk_CLIENTE_PESSOA`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `hotel`.`PESSOA` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`FATURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`FATURA` (
  `idFatura` INT NOT NULL AUTO_INCREMENT,
  `dataVencimento` DATE NOT NULL,
  `valor` DECIMAL(5,2) NOT NULL,
  `pagamento` TINYINT(1) NOT NULL DEFAULT true,
  PRIMARY KEY (`idFatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`RESERVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`RESERVA` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `dataInicio` DATE NOT NULL,
  `dataFinal` DATE NOT NULL,
  `situacao` VARCHAR(10) NOT NULL,
  `idCliente` INT NOT NULL,
  `idFatura` INT NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_RESERVA_CLIENTE` (`idCliente` ASC),
  INDEX `fk_RESERVA_FATURA` (`idFatura` ASC),
  CONSTRAINT `fk_RESERVA_CLIENTE`
    FOREIGN KEY (`idCliente`)
    REFERENCES `hotel`.`CLIENTE` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVA_FATURA`
    FOREIGN KEY (`idFatura`)
    REFERENCES `hotel`.`FATURA` (`idFatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`RESERVA_QUARTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`RESERVA_QUARTO` (
  `idTipoQuarto` INT NOT NULL,
  `idReserva` INT NOT NULL,
  `numQuartos` TINYINT NOT NULL,
  `numAdultos` TINYINT NOT NULL,
  PRIMARY KEY (`idTipoQuarto`, `idReserva`),
  INDEX `fk_TIPOQUARTO_has_RESERVA_TIPOQUARTO` (`idTipoQuarto` ASC),
  INDEX `fk_TIPOQUARTO_has_RESERVA_RESERVA` (`idReserva` ASC),
  CONSTRAINT `fk_TIPOQUARTO_has_RESERVA_TIPOQUARTO`
    FOREIGN KEY (`idTipoQuarto`)
    REFERENCES `hotel`.`TIPOQUARTO` (`idTipoQuarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TIPOQUARTO_has_RESERVA_RESERVA`
    FOREIGN KEY (`idReserva`)
    REFERENCES `hotel`.`RESERVA` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `hotel`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`USUARIO` (
  `login` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `perfil` ENUM('RECEPCIONISTA','CAMAREIRA','GARCON','GERENTE') NOT NULL,
  `idHotel` INT NOT NULL,
  PRIMARY KEY (`login`),
  INDEX `fk_USUARIO_HOTEL` (`idHotel` ASC),
  CONSTRAINT `fk_USUARIO_HOTEL`
    FOREIGN KEY (`idHotel`)
    REFERENCES `hotel`.`HOTEL` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`HOSPEDAGEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`HOSPEDAGEM` (
  `idHospedagem` INT NOT NULL AUTO_INCREMENT,
  `dataEntrada` DATE NOT NULL,
  `dataSaidaPrevista` DATE NOT NULL,
  `dataSaida` DATE NOT NULL,
  `idQuarto` INT NOT NULL,
  `idFatura` INT NULL,
  `USUARIO_login` VARCHAR(10) NULL,
  PRIMARY KEY (`idHospedagem`),
  INDEX `fk_HOSPEDAGEM_QUARTO` (`idQuarto` ASC),
  INDEX `fk_HOSPEDAGEM_FATURA` (`idFatura` ASC),
  INDEX `fk_HOSPEDAGEM_USUARIO` (`USUARIO_login` ASC),
  CONSTRAINT `fk_HOSPEDAGEM_QUARTO`
    FOREIGN KEY (`idQuarto`)
    REFERENCES `hotel`.`QUARTO` (`idQuarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HOSPEDAGEM_FATURA`
    FOREIGN KEY (`idFatura`)
    REFERENCES `hotel`.`FATURA` (`idFatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HOSPEDAGEM_USUARIO`
    FOREIGN KEY (`USUARIO_login`)
    REFERENCES `hotel`.`USUARIO` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`HOSPEDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`HOSPEDE` (
  `idHospede` INT NOT NULL AUTO_INCREMENT,
  `idHospedagem` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  PRIMARY KEY (`idHospede`),
  INDEX `fk_HOSPEDE_HOSPEDAGEM` (`idHospedagem` ASC),
  INDEX `fk_HOSPEDE_PESSOA` (`idPessoa` ASC),
  CONSTRAINT `fk_HOSPEDE_HOSPEDAGEM`
    FOREIGN KEY (`idHospedagem`)
    REFERENCES `hotel`.`HOSPEDAGEM` (`idHospedagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HOSPEDE_PESSOA`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `hotel`.`PESSOA` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`TELEFONE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`TELEFONE` (
  `idTelefone` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(15) NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idTelefone`),
  INDEX `fk_TELEFONE_CLIENTE` (`idCliente` ASC),
  CONSTRAINT `fk_TELEFONE_CLIENTE`
    FOREIGN KEY (`idCliente`)
    REFERENCES `hotel`.`CLIENTE` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`TABELA_PREÇO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`TABELA_PREÇO` (
  `idTABELA_PRECO` INT NOT NULL AUTO_INCREMENT,
  `valorDiaria` DECIMAL(5,2) NOT NULL,
  `tipoOcupacao` ENUM('SINGLE','DOUBLE','TRIPLE','FAMILY') NOT NULL,
  `idTipoQuarto` INT NOT NULL,
  PRIMARY KEY (`idTABELA_PRECO`),
  INDEX `fk_TABELA_PREÇO_TIPOQUARTO` (`idTipoQuarto` ASC),
  CONSTRAINT `fk_TABELA_PREÇO_TIPOQUARTO`
    FOREIGN KEY (`idTipoQuarto`)
    REFERENCES `hotel`.`TIPOQUARTO` (`idTipoQuarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`AMENIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`AMENIDADE` (
  `idAmenidade` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAmenidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`ITEM_AMENIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`ITEM_AMENIDADE` (
  `idITEM_AMENIDADE` INT NOT NULL AUTO_INCREMENT,
  `quantidade` SMALLINT NOT NULL,
  `idAmenidade` INT NOT NULL,
  `idTipoQuarto` INT NOT NULL,
  PRIMARY KEY (`idITEM_AMENIDADE`),
  INDEX `fk_ITEM_AMENIDADE_AMENIDADE` (`idAmenidade` ASC),
  INDEX `fk_ITEM_AMENIDADE_TIPOQUARTO` (`idTipoQuarto` ASC),
  CONSTRAINT `fk_ITEM_AMENIDADE_AMENIDADE`
    FOREIGN KEY (`idAmenidade`)
    REFERENCES `hotel`.`AMENIDADE` (`idAmenidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEM_AMENIDADE_TIPOQUARTO`
    FOREIGN KEY (`idTipoQuarto`)
    REFERENCES `hotel`.`TIPOQUARTO` (`idTipoQuarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
